#! /usr/bin/env python

import os
import sys

# Get current directory
cur_dir, _ = os.path.split(__file__)

# Modify the python path
python_path = os.environ.get('PYTHONPATH', '')
python_dir = os.path.join(cur_dir, 'python')

os.environ['PYTHONPATH'] =  python_dir + os.pathsep + python_path

# Run our python program
os.execvp(sys.executable, [sys.executable, '-m', 'xpkg.main'] + sys.argv[1:])
